name: BungeeTeleport
main: au.com.addstar.btb.BungeeTeleport
version: ${project.version}
author: add5tar
description: Partner plugin for BungeeTeleport

commands:
  truehardcore:
    aliases: btb
    description: BungeeTeleportBukkit command
    
permissions:
  bungeeteleport.admin:
    description: Full admin access for BungeeTeleportBukkit
    default: op
